---
# ------------------------------------------------------------------------
# handlers file for ssh_server
# ------------------------------------------------------------------------

- name: restart ssh_server
  service:
    name: "{{ ssh_server_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
